
export const SELECTION = 'selection';

export const UPDATE_SELECTION_SUCCESS = `${SELECTION}/UPDATE_SELECTION_SUCCESS`;
export const UPDATE_SELECTION_FAILURE = `${SELECTION}/UPDATE_SELECTION_FAILURE`;

export const RESET_SELECTION_SUCCESS = `${SELECTION}/RESET_SELECTION_SUCCESS`;
export const RESET_SELECTION_FAILURE = `${SELECTION}/RESET_SELECTION_FAILURE`;

export const TRANSFORM_SELECTION = `${SELECTION}/TRANSFORM_SELECTION`;
export const TRANSFORM_SELECTION_FAILURE = `${SELECTION}/TRANSFORM_SELECTION_FAILURE`;

export const COMMIT_SELECTION_SUCCESS = `${SELECTION}/COMMIT_SELECTION_SUCCESS`;
export const COMMIT_SELECTION_FAILURE = `${SELECTION}/COMMIT_SELECTION_FAILURE`;

export const SELECT_POSITION_SUCCESS = `${SELECTION}/SELECT_POSITION_SUCCESS`;
export const SELECT_POSITION_FAILURE = `${SELECTION}/SELECT_POSITION_FAILURE`;

export const DELETE_SELECTION_SUCCESS = `${SELECTION}/DELETE_SELECTION_SUCCESS`;
export const DELETE_SELECTION_FAILURE = `${SELECTION}/DELETE_SELECTION_FAILURE`;

export const UPDATE_SELECTION_PADDING = `${SELECTION}/UPDATE_SELECTION_PADDING`;
export const UPDATE_SELECTION_PADDING_FAILURE = `${SELECTION}/UPDATE_SELECTION_PADDING_FAILURE`;
