
export const TEXT = 'text';

export const CREATE_TEXT_FAILURE = `${TEXT}/CREATE_TEXT_FAILURE`;
export const CREATE_TEXT_SUCCESS = `${TEXT}/CREATE_TEXT_SUCCESS`;

export const UPDATE_TEXT_SUCCESS = `${TEXT}/UPDATE_TEXT_SUCCESS`;
export const UPDATE_TEXT_FAILURE = `${TEXT}/UPDATE_TEXT_FAILURE`;

export const UPDATE_TEXT_VALUE_SUCCESS = `${TEXT}/UPDATE_TEXT_VALUE_SUCCESS`;
export const UPDATE_TEXT_VALUE_FAILURE = `${TEXT}/UPDATE_TEXT_VALUE_FAILURE`;

export const CHANGE_FONT_FAMILY_SUCCESS = `${TEXT}/CHANGE_FONT_FAMILY_SUCCESS`;
export const CHANGE_FONT_FAMILY_FAILURE = `${TEXT}/CHANGE_FONT_FAMILY_FAILURE`;

export const CHANGE_FONT_SIZE_SUCCESS = `${TEXT}/CHANGE_FONT_SIZE_SUCCESS`;
export const CHANGE_FONT_SIZE_FAILURE = `${TEXT}/CHANGE_FONT_SIZE_FAILURE`;

export const CREATE_TEXT_AS_CURRENT_SELECTION_SUCCESS = `${TEXT}/CREATE_TEXT_AS_CURRENT_SELECTION_SUCCESS`;
export const CREATE_TEXT_AS_CURRENT_SELECTION_FAILURE = `${TEXT}/CREATE_TEXT_AS_CURRENT_SELECTION_FAILURE`;

export const DELETE_ALL_TEXT_SUCCESS = `${TEXT}/DELETE_ALL_TEXT_SUCCESS`;
export const DELETE_ALL_TEXT_FAILURE = `${TEXT}/DELETE_ALL_TEXT_FAILURE`;

export const LOAD_TEXT_DATA = `${TEXT}/LOAD_TEXT_DATA`;
export const LOAD_TEXT_DATA_FAILURE = `${TEXT}/LOAD_TEXT_DATA_FAILURE`;

export const CHANGE_FONT_PATH_SUCCESS = `${TEXT}/CHANGE_FONT_PATH_SUCCESS`;
export const CHANGE_FONT_PATH_FAILURE = `${TEXT}/CHANGE_FONT_PATH_FAILURE`;

export const Fonts = {
    OpenBaskerville: 'Open Baskerville',
    SourceSans: 'Source Sans Pro'
};
