
export const APP = 'app';

export const SET_ACCENT_COLOR = `${APP}/SET_ACCENT_COLOR`;
export const SET_ACCENT_COLOR_FAILURE = `${APP}/SET_ACCENT_COLOR_FAILURE`;

export const LOAD_APP_DATA = `${APP}/LOAD_APP_DATA`;
export const LOAD_APP_DATA_FAILURE = `${APP}/LOAD_APP_DATA_FAILURE`;

export const SET_LOGO_IMAGE = `${APP}/SET_LOGO_IMAGE`;
export const SET_LOGO_IMAGE_FAILURE = `${APP}/SET_LOGO_IMAGE_FAILURE`;

export const SET_IMAGE = `${APP}/SET_IMAGE`;
export const SET_IMAGE_FAILURE = `${APP}/SET_IMAGE_FAILURE`;

export const UNSET_IMAGE = `${APP}/UNSET_IMAGE`;
export const UNSET_IMAGE_FAILURE = `${APP}/UNSET_IMAGE_FAILURE`;

export const SET_STROKE_WIDTH = `${APP}/SET_STROKE_WIDTH`;
export const SET_STROKE_WIDTH_FAILURE = `${APP}/SET_STROKE_WIDTH_FAILURE`;

export const SET_EXPORT_KIND = `${APP}/SET_EXPORT_KIND`;
export const SET_EXPORT_KIND_FAILURE = `${APP}/SET_EXPORT_KIND_FAILURE`;

export const SET_ARTBOARD_PRESET = `${APP}/SET_ARTBOARD_PRESET`;
export const SET_ARTBOARD_PRESET_FAILURE = `${APP}/SET_ARTBOARD_PRESET_FAILURE`;

export const SET_ACTIVE_ARTBOARD_PRESET = `${APP}/SET_ACTIVE_ARTBOARD_PRESET`;

export const SET_PRINT_ROTATION = `${APP}/SET_PRINT_ROTATION`;
export const SET_PRINT_ROTATION_FAILURE = `${APP}/SET_PRINT_ROTATION_FAILURE`;

export const TOGGLE_FEATURE = `${APP}/TOGGLE_FEATURE`;
export const TOGGLE_FEATURE_FAILURE = `${APP}/TOGGLE_FEATURE_FAILURE`;

export const SET_BACKGROUND_IMAGE = `${APP}/SET_BACKGROUND_IMAGE`;
export const SET_BACKGROUND_IMAGE_FAILURE = `${APP}/SET_BACKGROUND_IMAGE_FAILURE`;

export const SET_WELCOME_VIDEO = `${APP}/SET_WELCOME_VIDEO`;
export const SET_WELCOME_VIDEO_FAILURE = `${APP}/SET_WELCOME_VIDEO_FAILURE`;

export const SET_USERNAME = `${APP}/SET_USERNAME`;
export const SET_USERNAME_FAILURE = `${APP}/SET_USERNAME_FAILURE`;

export const ExportKind = {
    PNG: 'png',
    SVG: 'svg',
    PRINT: 'print',
    UPLOAD: 'upload'
};
