
export const PATHS = 'paths';

export const CREATE_PATH_SUCCESS = `${PATHS}/CREATE_PATH_SUCCESS`;
export const CREATE_PATH_FAILURE = `${PATHS}/CREATE_PATH_FAILURE`;

export const DELETE_PATHS_SUCCESS = `${PATHS}/DELETE_PATHS_SUCCESS`;
export const DELETE_PATHS_FAILURE = `${PATHS}/DELETE_PATHS_SUCCESS`;
