
export const IMAGES = 'images';

export const CREATE_IMAGE = `${IMAGES}/CREATE_IMAGE`;
export const CREATE_IMAGE_FAILURE = `${IMAGES}/CREATE_IMAGE_FAILURE`;

export const DELETE_ALL_IMAGES = `${IMAGES}/DELETE_ALL_IMAGES`;
export const DELETE_ALL_IMAGES_FAILURE = `${IMAGES}/DELETE_ALL_IMAGES_FAILURE`;

export const CREATE_IMAGE_AS_CURRENT_SELECTION = `${IMAGES}/CREATE_IMAGE_AS_CURRENT_SELECTION`;
export const CREATE_IMAGE_AS_CURRENT_SELECTION_FAILURE = `${IMAGES}/CREATE_IMAGE_AS_CURRENT_SELECTION_FAILURE`;

export const SELECT_IMAGE_PATH = `${IMAGES}/SELECT_IMAGE_PATH`;
export const SELECT_IMAGE_PATH_FAILURE = `${IMAGES}/SELECT_IMAGE_PATH_FAILURE`;
